In [1]:
# import
import csv
import math
import random
import sys
import numpy as np
from pystruct.models import ChainCRF
from pystruct.learners import FrankWolfeSSVM

random.seed

<bound method Random.seed of <random.Random object at 0x10403c618>>

In [2]:
# extract data

i = -1

data_num = 2000 - 605 # 1395

wifi_loc_time = np.zeros(shape = (data_num, 523))

# 520 WAP
# FLOOR 2
# Building 1
# timestamp

# total data num = 19938

with open("1478167720_9233432_trainingData.csv", newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',')
    for row in spamreader:
        if (row[523] == 'BUILDINGID'):
            continue
        elif (row[523] is not '1' or row[522] is not '2'):
            continue
        i = i+1
        if (i > data_num):
            break
        # wifi
        wifi_loc_time[i-1][:520] = np.array(row[:520])
        # location x, y
        wifi_loc_time[i-1][520:522] = np.array(row[520:522])
        # time stamp
        wifi_loc_time[i-1][-1] = np.array(row[-1])



In [3]:
# sort by timestamp
# https://stackoverflow.com/questions/2828059/sorting-arrays-in-numpy-by-column
wifi_loc_time = wifi_loc_time[wifi_loc_time[:,-1].argsort()]

In [4]:
batch_num = 9
batch_wifi_train = np.zeros((int(data_num/(batch_num)), batch_num, 520))
batch_loc_train = np.zeros((int(data_num/(batch_num)), batch_num), dtype = int)

In [5]:
# produce location list - length 79
######################### location_list = np.unique(wifi_loc_time[:, 520:521])
location_list = []
for i in range(data_num):
    if wifi_loc_time[i][520:521] not in location_list:
        location_list.append(float(wifi_loc_time[i][520:521]))

location_list = np.asarray(location_list)

loc_dict = {}
for i in range(len(location_list)):
    loc_dict[location_list[i]] = i
#print(loc_dict)

In [6]:

for i in range(data_num):
    print(i, int(i/batch_num),i%batch_num)
    batch_wifi_train[int(i/(batch_num))][i%batch_num] = wifi_loc_time[i][:520]
    batch_loc_train[int(i/(batch_num)),i%batch_num] = loc_dict[float(wifi_loc_time[i][520:521])]
    #print(loc_dict[float(wifi_loc_time[i][520:521])])

0 0 0
1 0 1
2 0 2
3 0 3
4 0 4
5 0 5
6 0 6
7 0 7
8 0 8
9 1 0
10 1 1
11 1 2
12 1 3
13 1 4
14 1 5
15 1 6
16 1 7
17 1 8
18 2 0
19 2 1
20 2 2
21 2 3
22 2 4
23 2 5
24 2 6
25 2 7
26 2 8
27 3 0
28 3 1
29 3 2
30 3 3
31 3 4
32 3 5
33 3 6
34 3 7
35 3 8
36 4 0
37 4 1
38 4 2
39 4 3
40 4 4
41 4 5
42 4 6
43 4 7
44 4 8
45 5 0
46 5 1
47 5 2
48 5 3
49 5 4
50 5 5
51 5 6
52 5 7
53 5 8
54 6 0
55 6 1
56 6 2
57 6 3
58 6 4
59 6 5
60 6 6
61 6 7
62 6 8
63 7 0
64 7 1
65 7 2
66 7 3
67 7 4
68 7 5
69 7 6
70 7 7
71 7 8
72 8 0
73 8 1
74 8 2
75 8 3
76 8 4
77 8 5
78 8 6
79 8 7
80 8 8
81 9 0
82 9 1
83 9 2
84 9 3
85 9 4
86 9 5
87 9 6
88 9 7
89 9 8
90 10 0
91 10 1
92 10 2
93 10 3
94 10 4
95 10 5
96 10 6
97 10 7
98 10 8
99 11 0
100 11 1
101 11 2
102 11 3
103 11 4
104 11 5
105 11 6
106 11 7
107 11 8
108 12 0
109 12 1
110 12 2
111 12 3
112 12 4
113 12 5
114 12 6
115 12 7
116 12 8
117 13 0
118 13 1
119 13 2
120 13 3
121 13 4
122 13 5
123 13 6
124 13 7
125 13 8
126 14 0
127 14 1
128 14 2
129 14 3
130 14 4
131 14 5
132 14 6
133

1208 134 2
1209 134 3
1210 134 4
1211 134 5
1212 134 6
1213 134 7
1214 134 8
1215 135 0
1216 135 1
1217 135 2
1218 135 3
1219 135 4
1220 135 5
1221 135 6
1222 135 7
1223 135 8
1224 136 0
1225 136 1
1226 136 2
1227 136 3
1228 136 4
1229 136 5
1230 136 6
1231 136 7
1232 136 8
1233 137 0
1234 137 1
1235 137 2
1236 137 3
1237 137 4
1238 137 5
1239 137 6
1240 137 7
1241 137 8
1242 138 0
1243 138 1
1244 138 2
1245 138 3
1246 138 4
1247 138 5
1248 138 6
1249 138 7
1250 138 8
1251 139 0
1252 139 1
1253 139 2
1254 139 3
1255 139 4
1256 139 5
1257 139 6
1258 139 7
1259 139 8
1260 140 0
1261 140 1
1262 140 2
1263 140 3
1264 140 4
1265 140 5
1266 140 6
1267 140 7
1268 140 8
1269 141 0
1270 141 1
1271 141 2
1272 141 3
1273 141 4
1274 141 5
1275 141 6
1276 141 7
1277 141 8
1278 142 0
1279 142 1
1280 142 2
1281 142 3
1282 142 4
1283 142 5
1284 142 6
1285 142 7
1286 142 8
1287 143 0
1288 143 1
1289 143 2
1290 143 3
1291 143 4
1292 143 5
1293 143 6
1294 143 7
1295 143 8
1296 144 0
1297 144 1
1298 144 2

In [7]:
# train = 40
# test = 5
#for i in batch_loc:
#    print(i)
#print(batch_loc_test)

In [8]:
# batch_wifi_test = []
# batch_loc_test = []

# batch_wifi_test.append(batch_wifi[0])
# batch_loc_test.append(batch_loc[0])

# for i in range(20, 45):
#     batch_wifi_test.append(batch_wifi[i])
#     batch_loc_test.append(batch_loc[i])
    
# for a in batch_loc_test:
#     print(a)
    
#batch_wifi_test = np.asarray(batch_wifi_test,)

In [9]:
# validate
# extract data

i = -1

data_num_v = 86 # 86 in validation dataset

wifi_loc_time_v = np.zeros(shape = (data_num_v, 523))

# 520 WAP
# FLOOR 2
# Building 1
# timestamp

# total data num = 19938

with open("1478167721_0345678_validationData.csv", newline='') as v_csvfile:
    spamreader_v = csv.reader(v_csvfile, delimiter=',')
    for row in spamreader_v:
        if (row[523] == 'BUILDINGID'):
            continue
        elif (row[523] is not '1' or row[522] is not '2'):
            continue
        i = i+1
        #if (i > data_num):
        #    break
        # wifi
        wifi_loc_time_v[i-1][:520] = np.array(row[:520])
        # location x, y
        wifi_loc_time_v[i-1][520:522] = np.array(row[520:522])
        # time stamp
        wifi_loc_time_v[i-1][-1] = np.array(row[-1])

In [10]:
# sort by timestamp
wifi_loc_time_v = wifi_loc_time_v[wifi_loc_time_v[:,-1].argsort()]

In [11]:
batch_num = 9
batch_wifi_v = np.zeros((int(data_num_v/batch_num)+1, batch_num, 520))
batch_loc_v = np.zeros((int(data_num_v/batch_num)+1, batch_num), dtype = int)

In [12]:
location_list_v = []
for i in range(data_num_v):
    if wifi_loc_time_v[i][520:521] not in location_list_v:
        location_list_v.append(float(wifi_loc_time_v[i][520:521]))

location_list_v = np.asarray(location_list_v)

min_dis = 0
max_ind = -1

loc_dict_v = {}
for i in location_list_v:
    min_dis = sys.float_info.max
    max_ind = -1
    for j in range(len(location_list)):
        distance = math.sqrt(pow(i-location_list[j],2))
        if (min_dis > distance):
            #print(min_dis)
            #print(distance)
            min_dis = distance
            max_ind = j
    #print(min_dis)  (see the distance between new and old coordinate )
    loc_dict_v[i] = max_ind
## should remove [0]

In [13]:
for i in range(data_num_v):
    if (int(i/batch_num) >= 9):
        break
    #print(int(i/batch_num),i%batch_num)
    batch_wifi_v[int(i/batch_num)+1][i%batch_num] = wifi_loc_time_v[i][:520]
    batch_loc_v[int(i/batch_num)+1,i%batch_num] = loc_dict_v[float(wifi_loc_time_v[i][520:521])]
    #print(loc_dict_v[float(wifi_loc_time_v[i][520:521])])

In [14]:
print(batch_loc_train[0])
print(batch_loc_v[0])
batch_loc_v[0] = batch_loc_train[0]
print(batch_loc_v)
#np.concatenate((batch_loc_v1, batch_loc_v2), axis=0)

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]
[[ 0  0  0  0  0  0  0  0  0]
 [41 23 45 43 56 71 39 75 22]
 [38 19 52 55 43 60 59 47 69]
 [34 40 38 24 27 17  2 51  4]
 [15 44 60 11 30 53 72 52 52]
 [22 54 53 16 27 70 70 38 27]
 [76 52 17 70 47  8 47 43 64]
 [40 48 14 53 16 50 24 51 49]
 [69 40 27 14 38 33 35 10 71]
 [10 41 12 60 62 40 14 16 19]]


In [ ]:
#batch_loc_train_ep
#batch_wifi_train_ep

In [ ]:
for i in range(10):
    iteration = i*100
    print(iteration)
    #model = ChainCRF()
    #ssvm = FrankWolfeSSVM(model=model, C=.1, max_iter=50)
    #ssvm.fit(batch_wifi_train, batch_loc_train)
    #score = ssvm.score(batch_wifi_v, batch_loc_v)
    print(i, score)

In [ ]:
ssvm.get_params()